<?
$request_body="<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:mall=\"http://mall.checkout.platform.nhncorp.com/\" xmlns:base=\"http://base.checkout.platform.nhncorp.com/\">
   <soapenv:Header/>
   <soapenv:Body>
      <mall:RequestReturnRequest>
         <base:AccessCredentials>
            <base:AccessLicense>".$accessLicense."</base:AccessLicense>
            <base:Timestamp>".$timestamp."</base:Timestamp>
            <base:Signature>".$signature."</base:Signature>
         </base:AccessCredentials>
         <base:RequestID></base:RequestID>
         <base:DetailLevel>".$detailLevel."</base:DetailLevel>
         <base:Version>".$version."</base:Version>
         <mall:ProductOrderID>".$sProductOrderID."</mall:ProductOrderID>
         <mall:ReturnReasonCode>".$sReturnReasonCode."</mall:ReturnReasonCode>
         <mall:CollectDeliveryMethodCode>".$sCollectDeliveryMethodCode."</mall:CollectDeliveryMethodCode>
         <mall:CollectDeliveryCompanyCode>".$sCollectDeliveryCompanyCode."</mall:CollectDeliveryCompanyCode>
         <mall:CollectTrackingNumber>".$sTrackingNumber."</mall:CollectTrackingNumber>
      </mall:RequestReturnRequest>
   </soapenv:Body>
</soapenv:Envelope>";
?>